#!/usr/bin/env python3
"""
gen_metamodel_json.py — emit data/metamodel.json from meta_model.yaml
=====================================================================
The web UI's "Meta-model" tab draws the registry's *own* schema (RegistryClass,
RegistryProperty, RegistryRule, ...). That structure used to be hand-typed in
index.html as `CLASSES`/`EDGES`, which drifted whenever meta_model.yaml changed
(e.g. when range/unit moved onto rules and UnitOfMeasure was removed).

meta_model.yaml is the single source of truth — it already generates
schema_registry_utils/models.py (gen-pydantic) and docs/model.md's ER diagram
(gen-erdiagram). This is a third generated view, consumed by the UI at runtime
like data/registry.json: the *structural* facts (which classes exist, whether
they're abstract, their own slots, their is_a parents) come from here, so they
can never drift again.

Purely presentational bits stay in the UI as small overlays keyed by class id:
the short `tag` label, the node `POS` layout, and the curated subset of named
relationships (HAS_PROPERTY, ...) the diagram chooses to draw.

Run:  python scripts/gen_metamodel_json.py
Output: data/metamodel.json
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
META_MODEL = ROOT / "meta_model.yaml"
OUT = ROOT / "data" / "metamodel.json"


def first_sentence(description: str) -> str:
    """A short blurb for the UI: the first sentence of a class description.
    Collapses the YAML-folded whitespace, then splits on a period followed by
    whitespace and a capital letter — so an inline "e.g. \"age\"." doesn't cut
    the sentence short."""
    text = re.sub(r"\s+", " ", (description or "").strip())
    if not text:
        return ""
    return re.split(r"(?<=\.)\s+(?=[A-Z])", text)[0]


def build() -> dict:
    schema = yaml.safe_load(META_MODEL.read_text())
    classes_def: dict = schema.get("classes", {})

    classes = []
    edges = []
    for name, cls in classes_def.items():
        classes.append({
            "id": name,
            "abstract": bool(cls.get("abstract", False)),
            # Own slots only — inheritance is shown via the is_a edge.
            "slots": list(cls.get("slots", []) or []),
            "desc": first_sentence(cls.get("description", "")),
        })
        parent = cls.get("is_a")
        if parent:
            edges.append({"from": name, "to": parent, "type": "isa"})

    return {
        "generated_from": "meta_model.yaml",
        "note": "Generated by scripts/gen_metamodel_json.py — do not edit by hand.",
        "classes": classes,
        "edges": edges,
    }


def main() -> None:
    import sys

    rendered = json.dumps(build(), indent=2) + "\n"

    if "--check" in sys.argv[1:]:
        # CI/pre-commit guard: fail if the committed file is out of date with
        # meta_model.yaml, mirroring scripts/gen_models.sh --check.
        current = OUT.read_text() if OUT.exists() else ""
        if current != rendered:
            print(f"ERROR: {OUT.relative_to(ROOT)} is out of date with "
                  f"meta_model.yaml. Run: python scripts/gen_metamodel_json.py")
            sys.exit(1)
        print(f"{OUT.relative_to(ROOT)} is up to date.")
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered)
    data = json.loads(rendered)
    print(f"Wrote {OUT.relative_to(ROOT)} "
          f"({len(data['classes'])} classes, {len(data['edges'])} is_a edges).")


if __name__ == "__main__":
    main()
