#!/usr/bin/env bash
#
# Regenerate the Mermaid ER diagram in docs/model.md from
# schemas/meta_model.yaml, via LinkML's own gen-erdiagram generator.
#
# This is a *logical* view (every object-valued slot is a relationship,
# regardless of physical storage) — complementary to scripts/update_graph.py,
# which draws the *physical* LadybugDB layout (inline classes flattened,
# multivalued class refs as edges only).
#
# Usage:
#   ./scripts/gen_erdiagram.sh           # rewrite docs/model.md in place
#   ./scripts/gen_erdiagram.sh --check   # exit 1 if the doc is out of date
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

SCHEMA="schemas/meta_model.yaml"
TARGET="docs/model.md"
START="<!-- ERDIAGRAM:START (generated by scripts/gen_erdiagram.sh — do not edit by hand) -->"
END="<!-- ERDIAGRAM:END -->"

if [ -x .venv/bin/gen-erdiagram ]; then
    GEN=.venv/bin/gen-erdiagram
else
    GEN=gen-erdiagram
fi

DIAGRAM="$(mktemp)"
NEW_DOC="$(mktemp)"
trap 'rm -f "$DIAGRAM" "$NEW_DOC"' EXIT

# gen-erdiagram pads each field line with trailing spaces; strip them.
"$GEN" "$SCHEMA" -f mermaid --no-metadata | sed -E 's/[[:space:]]+$//' > "$DIAGRAM"

awk -v start="$START" -v end="$END" -v diagram_file="$DIAGRAM" '
    $0 == start { print; print "```mermaid"; while ((getline line < diagram_file) > 0) print line; print "```"; skip=1; next }
    $0 == end   { print; skip=0; next }
    !skip
' "$TARGET" > "$NEW_DOC"

if [ "${1:-}" = "--check" ]; then
    if diff -u "$TARGET" "$NEW_DOC"; then
        echo "$TARGET's ER diagram is up to date with $SCHEMA."
    else
        echo ""
        echo "ERROR: $TARGET's ER diagram is out of date with $SCHEMA."
        echo "Run ./scripts/gen_erdiagram.sh and commit the result."
        exit 1
    fi
else
    cp "$NEW_DOC" "$TARGET"
    echo "Updated $TARGET's ER diagram from $SCHEMA."
fi
